# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('nat64-example', ['nat64','core'])
    obj.source = 'nat64-example.cc'
    obj = bld.create_ns3_program('natexample', ['nat64','core'])
    obj.source = 'natexample.cc'
